# Generated by Django 3.1.3 on 2020-11-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50, unique=True)),
                ('body', models.TextField(blank=True, verbose_name='Page content')),
                ('update_date', models.DateTimeField(blank=True, verbose_name='Last Updated')),
            ],
        ),
    ]
